# Example configuration for Terragrunt GCP MCP Tool with Experimental Features
# Copy this file to config.yaml and update with your settings

# GCP Configuration
gcp:
  project_id: "your-project-id"
  credentials_path: "/path/to/your/credentials.json"  # Optional, can use ADC instead
  default_region: "europe-west2"
  default_zone: "europe-west2-a"

# Terragrunt Configuration
terragrunt:
  root_path: "../terragrunt-gcp-org-automation"  # Path to your terragrunt infrastructure
  binary_path: "terragrunt"  # Path to terragrunt binary
  terraform_binary: "tofu"   # OpenTofu binary
  cache_dir: ".terragrunt-cache"
  parallelism: 10
  timeout: 3600  # 1 hour timeout
  
  # New CLI redesign settings
  backend_bootstrap: true     # Enable automatic backend resource provisioning
  non_interactive: true       # Run in non-interactive mode (uses TG_NON_INTERACTIVE)
  use_run_command: true       # Use 'run' command prefix for operations
  
  # Advanced settings
  max_retries: 3              # Maximum retries for failed operations
  retry_delay: 5              # Delay between retries in seconds
  
  # Experimental features configuration
  experimental:
    # Stacks feature (experimental)
    stacks_enabled: true                    # Enable Terragrunt stacks experimental feature
    enhanced_dependency_resolution: true    # Use enhanced dependency resolution
    parallel_execution: true                # Enable parallel execution within stacks
    stack_outputs: true                     # Enable stack-level outputs
    recursive_stacks: false                 # Enable recursive stacks (not yet stable)
    
    # Stack execution settings
    max_parallel_units: 10                  # Maximum number of units to execute in parallel
    stack_timeout: 7200                     # Timeout for stack operations in seconds (2 hours)
    continue_on_error: false                # Continue stack execution on unit errors
    
    # Advanced experimental features
    auto_retry: true                        # Automatically retry failed units
    max_retries: 3                          # Maximum number of retries for failed units
    retry_delay: 30                         # Delay between retries in seconds

# Slack Configuration (optional)
slack:
  webhook_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  default_channel: "#infrastructure"
  username: "Terragrunt Bot"
  icon_emoji: ":terraform:"

# Monitoring Configuration
monitoring:
  enabled: true
  check_interval: 300  # 5 minutes
  max_retries: 3
  alert_thresholds:
    cost_increase_percent: 20.0
    deployment_duration_minutes: 30.0
    error_rate_percent: 5.0
    stack_failure_rate_percent: 10.0  # New threshold for stack failures

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: null  # Optional: "/var/log/terragrunt-gcp-mcp.log"
  max_file_size: "10MB"
  backup_count: 5 